name: octagon_africa
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  async_redux: ^15.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.0
  google_nav_bar: ^5.0.6
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  pin_code_text_field: ^1.8.0
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/